# Generated by Django 2.2 on 2019-04-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeds',
            old_name='image_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='feeds',
            name='title',
        ),
    ]
