# Generated by Django 2.2 on 2019-04-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectandscan_url',
            options={},
        ),
    ]
