# Generated by Django 2.2 on 2019-04-19 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scan', '0002_auto_20190419_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectandscan_url',
            options={'verbose_name': '动态', 'verbose_name_plural': '动态'},
        ),
    ]
